/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import supplementary.CDT_portredir;
import supplementary.GP;
import supplementary.HelpM;
import supplementary.OUT;

/**
 *
 * @author KOCMOC
 */
public class RedirectionPanelAuto extends javax.swing.JFrame implements OUT {

    private final String REDIRECTIONS_FILE = "redirections.txt";
    private ArrayList<RedirectionEntry> redirectionsList = new ArrayList<RedirectionEntry>();
    public ArrayList<MyPortRedirection> portRedirectionList = new ArrayList<MyPortRedirection>();
    

    /**
     * Creates new form RedirectionPanelAuto
     */
    public RedirectionPanelAuto() {
        initComponents();
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        this.setIconImage(new ImageIcon(GP.IMAGE_ICON_URL).getImage());
        this.setTitle("MyPortRedirect Auto");
        //#BOUT#OLD#
        // SUPER IMPORTANT - THIS will start the program but the redirections will not start
        // OBS! Since 2024-03-01 it's moved the go() method of MyPortRedirection.java line 107
//        if (HelpM.checkDAC_D("2024-03-20") == false) {
//            return;
//        }
        //#BOUT#USING-THREAD#INIT#IMPLEMNTED#2024-03-26#
        // FIRST arg: "check-interval in minutes", should be more then 20 when distributed..
        // SECOND arg: is the "bout-date" Just don't touch it and change it from the "xta_.java"
        // OBS! Don't forget to use the OBFUSCATED .jar
        // OBS! Don't forget to disable "bout-debug-outputs" to console: search for #BOUT#OUTPUT-TO-CONSOLE#
        // OBS! REMEMBER if the name of button is "Stop redirections" with small "r" it means that the bout was triggered
        CDT_portredir cdt = new CDT_portredir(368, CDT_portredir.get()); // 37
        //
        go();
    }

    private void go() {
        try {
            readFromFileIntoList();
        } catch (Exception ex) {
            Logger.getLogger(RedirectionPanelAuto.class.getName()).log(Level.SEVERE, null, ex);
            showMessage("Reading from: " + REDIRECTIONS_FILE + " failed");
        }
        //
        startRedirections();
    }

    public void stopRedirections() {
        for (MyPortRedirection mpr : portRedirectionList) {
            mpr.closeServerSocket();
            mpr.killAllClients();
            portRedirectionList.remove(mpr);
        }
    }

    public void startRedirections() {
        for (RedirectionEntry re : redirectionsList) {
            //
            showMessage(re.srcPort + " --> " + re.destHost + ": " + re.destPort);
            //
            MyPortRedirection mpr = new MyPortRedirection(re.srcPort, re.destHost, re.destPort, this);
            portRedirectionList.add(mpr);
            //
            Thread x = new Thread(mpr);
            x.setName("PortRedirection: " + re.srcPort);
            x.start();
        }
        System.out.println("");
    }

    private void readFromFileIntoList() throws Exception {
        ArrayList<String> list;
        list = HelpM.read_Txt_To_ArrayList(REDIRECTIONS_FILE);
        //
        for (String line : list) {
            String[] arr = line.split(" ");
            //
            int srcPort = Integer.parseInt(arr[0]);
            String destHost = arr[1];
            int destPort = Integer.parseInt(arr[2]);
            //
            RedirectionEntry re = new RedirectionEntry(srcPort, destHost, destPort);
            //
            redirectionsList.add(re);
        }
    }

    @Override
    public void showMessage(String msg) {
        jTextArea1.append(HelpM.get_proper_date_time_same_format_on_all_computers() + "   " + msg + "\n");
    }

    @Override
    public void updateStatus(String status) {
        jLabel3.setText(status);
    }

    @Override
    public void updateClientCount(int clients) {
        if (clients > 0) {
            updateStatus("active");
        } else {
            updateStatus("listening");
        }
        //
        jLabel5.setText("" + clients);
    }

    private synchronized void wait_(int millis) {
        try {
            wait(millis);
        } catch (InterruptedException ex) {
            Logger.getLogger(RedirectionPanelAuto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    class RedirectionEntry {

        public int srcPort;
        public String destHost;
        public int destPort;

        public RedirectionEntry(int srcPort, String destHost, int destPort) {
            this.srcPort = srcPort;
            this.destHost = destHost;
            this.destPort = destPort;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton_stop_redirections = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton2_Exit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton_stop_redirections.setText("Stop Redirections");
        jButton_stop_redirections.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_stop_redirectionsActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("PortRedirection Auto");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Status:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("...");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Clients:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("...");

        jButton2_Exit.setText("EXIT");
        jButton2_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2_ExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_stop_redirections, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(79, 79, 79)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 32, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2_Exit)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(45, 45, 45)
                .addComponent(jButton_stop_redirections)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2_Exit)
                .addGap(7, 7, 7))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_stop_redirectionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_stop_redirectionsActionPerformed
        stopRedirections();
    }//GEN-LAST:event_jButton_stop_redirectionsActionPerformed

    private void jButton2_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2_ExitActionPerformed
        if (HelpM.confirm("Please confirm action")) {
            System.exit(0);
        }
    }//GEN-LAST:event_jButton2_ExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RedirectionPanelAuto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RedirectionPanelAuto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RedirectionPanelAuto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RedirectionPanelAuto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //#BOUT#OLD#
        // OBS!!! HelpM.checkDac_c not longer used look in the Constructor for checkDac_D
//        HelpM.checkDAC_c__with_file_check__NOT_SUITABLE_FOR_MCLAUNCHER("2024-04-15"); // 2024-04-15
        //
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new RedirectionPanelAuto().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton jButton2_Exit;
    public static javax.swing.JButton jButton_stop_redirections;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
